### ISSUE TITLE
EPIC: Angular application architecture

### ISSUE THREAD

**Issue by bojjakaseenadhreddy** [bojjakaseenadhreddy/e-calendar#1]
# Create Angular application

- [ ] Integrate Nx Console
- [ ] Integrate Jest and validate
- [ ] Integrate Cypress e2e test and validate
- [ ] Configure ES lint
- [ ] Configure git hooks (husky)
- [ ] Integrate NgRx store
- [ ] Add i18
- [ ] Integrate Docker
- [ ] Configure Vercel environment
- [ ] Create CI/CD pipeline for deployment on merge

## Acceptance criteria

- App should run
- Integration tests (jest) should pass and generate coverage report
- e2e tests (cypress) should pass and generate the coverage report
- Able to generate components and libs with Nx plugin in IDEs
- Run the lint and auto-fix if any syntax errors are there
- Configure husky to auto-format code before the commit
- Fail the commit if code syntax is not following the ES lint guidelines
- Integrate NgRx store for data sharing between components
- Integrate internationalization languages (en & fr)
- App should run on any machines without any further libraries (Docker required)
- Configure Vercel for deployment and managing env values
- Configure CI/CD for auto-deployment
